server:
  port: ${SERVER_PORT}
spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:native}
  application:
    name: ${SPRING_APPLICATION_NAME}
  cloud:
    config:
      server:
        native:
          search-locations: ${CONFIG_SEARCH_LOCATIONS:classpath:/configurations}
